# Generated by Django 6.0.3 on 2026-03-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = []
