# Generated by Django 6.0.3 on 2026-03-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
