# Generated by Django 6.0.3 on 2026-03-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_propertyimage_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyimage",
            name="image_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
