# Generated by Django 5.0.6 on 2026-03-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_alter_propertyimage_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="propertyimage",
            name="image_file",
            field=models.FileField(blank=True, null=True, upload_to="property_images/"),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
