# Generated by Django 5.0.6 on 2026-03-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agent",
            name="phone",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
